---
author: "Yuhao Kang"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r}   
# task 1: list one size-9 itemset that includes Class=edible
library(arules)
data("Mushroom")
itemsets <- apriori(Mushroom,
                    parameter = list(minlen=9, maxlen=9,
                                     target='frequent'))
                    
inspect(sort(subset(itemsets,items %in% 'Class=edible'),by='support',decreasing = T)[1:5])
```

```{r}
#task 2
# A partial white-veiled mushroom with broad, closely spaced gills.  
rule1 <- apriori(Mushroom,
                 parameter = list(minlen=5,maxlen=6,
                                  target='rules'
                 ))
inspect(subset(rule1, subset=lhs %ain% c("VeilColor=white","GillSize=broad","VeilType=partial",
                                         "GillSpace=close")& rhs %in% c("Class=poisonous","Class=edible" )))
#mushroom 1:Information is not enough, cannot determine whether it is edible or not.
```

```{r}
#A partial white-veiled mushroom with closely spaced gills, a single ring and a silky surface below the ring.  
rule2 <- apriori(Mushroom,
                 parameter = list(minlen=6,maxlen=6,
                                  target='rules'
                 ))
inspect(subset(rule2, subset=lhs %ain% c("VeilColor=white","VeilType=partial","RingNumber=one",
                                         "GillSpace=close","SurfaceBelowRing=silky")
                                         & rhs %in% c("Class=poisonous","Class=edible" )))
#mushroom 2:It is poisonous.
```

```{r}
#A mushroom with smooth surface above the ring.
rule3 <- apriori(Mushroom,
                 parameter = list(minlen=2,maxlen=3,
                                  target='rules'
                 ))
inspect(subset(rule3, subset=lhs %in% "SurfaceAboveRing=smooth"& rhs %in% c("Class=poisonous","Class=edible" )))
# mushroom 3:There is high possibility that it is edible.
```

